---
title: "task1"
author: "Md. Azmir Alam"
date: "2022-12-20"
output: html_document
---


####Import dataset and preview.
```{r}

#install.packages("readr")
library(readr)
data <- 	read_csv("student_scores - student_scores.csv",show_col_types=FALSE)

data
head(data)

```
####Draw a plot of the data.
```{r}

#install.packages("ggplot2")


plot(data)

```

####Describe the dataset.

```{r}

dim(data)
summary(data)
```

####checking correlation.

```{r}

data=data.frame(data,check.rows = TRUE)
cor(data)
```

####Create model.
```{r}

fit_1<- lm(Scores~Hours,data=data)
summary(fit_1)
```

####Spliting train and test data set and build the model.
```{r}

#install.packages("caTools")
library(caTools)
set.seed(42)
sampleSplit <- sample.split(Y=data$Scores, SplitRatio=0.7)
trainSet <- subset(x=data, sampleSplit==TRUE)
testSet <- subset(x=data, sampleSplit==FALSE)
print(dim(trainSet))
print(dim(testSet))
model <- lm(Scores ~ Hours , data=trainSet)

```
####Check the residuals of the model.
```{r}

library(ggplot2)
modelResiduals <- as.data.frame(residuals(model)) 
ggplot(modelResiduals, aes(residuals(model))) +
  geom_histogram(fill='68', color='black')
```
####Visualize the regression line.


```{r}

library(ggplot2)
ggplot(data, aes(x = Hours, y = Scores)) +
        geom_point(aes(color = Scores)) +
        stat_smooth(method = "lm",
        col = "orange", se = FALSE, size = .5
)


```


#### comparing the predicted with actual value.

```{r}


pred <- predict(model, testSet)
results <- cbind(pred,testSet$Scores) 
colnames(results) <- c('pred','real')
results <- as.data.frame(results)
results



```
####prediction of score when a student study 9.25 hrs per day.
```{r}


Hours <- 9.5
Hours <-as.data.frame(Hours)
predicted_score <- predict(model, Hours)
print(predicted_score)


```
